version: '3.8'

services:
  streamlit:
    build: .
    ports:
      - "8501:8501"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - streamlit
    networks:
      - app-network

networks:
  app-network:
